# Generated by Django 3.0.6 on 2020-06-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='model',
            new_name='name',
        ),
    ]
