# Generated by Django 3.0.6 on 2020-06-15 05:48

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200615_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=articles.models.image_article_path),
        ),
    ]
