# Generated by Django 3.0.6 on 2020-06-22 23:57

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200615_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to=articles.models.image_article_path),
        ),
    ]
