# Generated by Django 3.0.6 on 2020-06-23 00:12

import articles.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20200623_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to=articles.models.image_article_path),
            preserve_default=False,
        ),
    ]
