# Generated by Django 3.0.6 on 2020-06-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200612_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.jpeg', null=True, upload_to='media/'),
        ),
    ]
