# Generated by Django 3.0.6 on 2020-06-15 04:33

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200615_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.photo_path),
        ),
    ]
